# Generated by Django 4.2.20 on 2025-03-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_category_restaurant_alter_fooditem_category_and_more'),
        ('home', '0006_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.fooditem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.fooditem'),
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
    ]
