# Generated by Django 4.2.20 on 2025-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('opening_hours', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
            ],
        ),
    ]
