# Generated by Django 4.2.20 on 2025-03-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
