# Generated by Django 4.2.20 on 2025-03-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_category_restaurant_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='category_restaurant', to='restaurant.restaurant'),
        ),
    ]
