# Generated by Django 4.2.20 on 2025-03-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='food_type',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10),
        ),
    ]
