# Generated by Django 4.2.20 on 2025-03-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_category_food_type_fooditem_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
    ]
